name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install flake8 mypy pytest pytest-cov

    - name: Linting (flake8)
      run: flake8 .

    - name: Type checking (mypy)
      run: mypy . || true

    - name: Ejecutar tests y cobertura
      run: pytest --cov=. --cov-report=term-missing

    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: reporte-cobertura
        path: .coverage
